#ifndef LINUXPLORER_ENGINEFWD_HPP_
#define LINUXPLORER_ENGINEFWD_HPP_

#ifdef LINUXPLORER_ENGINE_API_IMPLEMENTATION
#define LINUXPLORER_ENGINE_API __declspec(dllexport)
#else
#define LINUXPLORER_ENGINE_API __declspec(dllimport)
#endif // LINUXPLORER_ENGINE_API_IMPLEMENTATION

#endif // LINUXPLORER_ENGINEFWD_HPP_