#ifndef LINUXPLORER_SSHFWD_HPP_
#define LINUXPLORER_SSHFWD_HPP_

#ifdef LINUXPLORER_SSH_API_IMPLEMENTATION
#define LINUXPLORER_SSH_API __declspec(dllexport)
#else
#define LINUXPLORER_SSH_API __declspec(dllimport)
#endif // LINUXPLORER_SHH_API_IMPLEMENTATION

#endif // LINUXPLORER_SSHFWD_HPP_