#ifndef LINUXPLORER_SHELLFWD_HPP_
#define LINUXPLORER_SHELLFWD_HPP_

#ifdef LINUXPLORER_SHELL_API_IMPLEMENTATION
#define LINUXPLORER_SHELL_API __declspec(dllexport)
#else
#define LINUXPLORER_SHELL_API __declspec(dllimport)
#endif // LINUXPLORER_SHELL_API_IMPLEMENTATION

#endif // LINUXPLORER_SHELLFWD_HPP_